nyc_transformation_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: training-gcp-484513
      dataset: nyc_data  # tables stg_* iront ici
      threads: 4
      timeout_seconds: 300
      location: EU
      keyfile: /opt/airflow/config/gcp/airflow-gcp-key.json

    prod:
      type: bigquery
      method: service-account
      project: training-gcp-484513
      dataset: nyc_data
      threads: 4
      timeout_seconds: 300
      location: EU
      keyfile: /opt/airflow/config/gcp/airflow-gcp-key.json