version: 2

sources:
  - name: staging_data
    database: training-gcp-484513
    schema: intermediate
    tables:
      - name: stg_311_requests
      - name: stg_traffic_speed
      - name: stg_for_hire_vehicule_trips
      - name: stg_high_volume_vehicule_trips
      - name: stg_yellow_taxi_trips
      - name: stg_weather
